/********************************************************************************
 * Copyright (c) 2014 CCNT
 * Version: 1.0
 * Author:zhongjinwen
 * Modified Time:2014-5-30 
 *******************************************************************************/

package zju.ccnt.xptools.inputmanager;

/**
 * The Class RawEvent. Represent the most basic event generated by devices.
 * The "type","code","value" is compatible with linux kernel definithon of
 * input_event, see the source file of /include/linux/input.h. 
 */
public class RawEvent {
	public long when;		//nanosecond of when the event happen
	public int deviceId;	//not that essencial because we only have one device.
	public int type;		//see /include/linux.input.h
	public int code;		//see /include/linux.input.h
	public int value;		//see /include/linux.input.h
	
	public RawEvent(long w,int d,int t,int c,int v){
		when=w;
		deviceId=d;
		type=t;
		code=c;
		value=v;
	}
	
	public RawEvent(){
		
	}
	
	@Override
	public String toString(){
		String s1=Integer.toHexString(type);
		String s2=Integer.toHexString(code);
		String s3=Integer.toHexString(value);
		return ""+s1+" "+s2+" "+s3;
	}
}
